Add deployment workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,12 +26,14 @@ jobs:
         # Optional: Debugging - Check if the service key file was written correctly
         cat "${HOME}/gcloud-service-key.json"
 
-        # Validate JSON format (ensure that it's correct and does not have issues)
-        jq empty "${HOME}/gcloud-service-key.json" || exit 1
-        
+        # Debugging JSON format to check if it's valid
+        echo "Validating JSON file..."
+        cat "${HOME}/gcloud-service-key.json" | jq . || { echo "Invalid JSON"; exit 1; }
+
         # Activate the service account and set the project
         gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
         gcloud config set project triple-env-447304-f9
+
 
     - name: Deploy to VM
       run: |
