Add deployment workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,6 +23,9 @@ jobs:
         # Save the service account key to a file
         echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcloud-service-key.json"
 
+        # ตรวจสอบเนื้อหาของไฟล์ JSON เพื่อให้แน่ใจว่าถูกต้อง
+        cat "${HOME}/gcloud-service-key.json"
+
         # Activate the service account and set the project
         gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"
         gcloud config set project triple-env-447304-f9
@@ -31,3 +34,11 @@ jobs:
       run: |
         # SSH into the VM and run the necessary commands
         gcloud compute ssh my-test-deploy --zone asia-southeast1-a --project triple-env-447304-f9 --command "cd /var/www/html/my-project && git pull && composer install && php artisan migrate"
+
+        # ตรวจสอบการเชื่อมต่อ SSH
+        if [ $? -eq 0 ]; then
+          echo "SSH connection and deployment successful"
+        else
+          echo "SSH connection failed"
+          exit 1
+        fi
